pub const ID_SIZE: usize = 32; // Blake256 of password
pub const HANDSHAKE_MSG_SIZE: usize = 33; // generated by Spake2
pub const BUFFER_SIZE: usize = 1024 * 1024; // chunk size for files sent over wire (1MB)
pub const NONCE_SIZE: usize = 96 / 8; // used for every encrypted message
pub const SESSION_ID_SIZE: usize = 8; // session ID for stream encryption (increased from 4)
pub const PASSWORD_LEN: usize = 16; // generated password length (~95 bits entropy with base62)
pub const ZSTD_COMPRESSION_LEVEL: i32 = 3; // zstd compression level for file transfers

// Network defaults
pub const DEFAULT_RELAY: &str = "174.138.70.74:8080";
pub const DEFAULT_BIND: &str = "0.0.0.0:8080";
pub const DEFAULT_MAX_CLIENTS: usize = 1000;
pub const DEFAULT_PEER_TIMEOUT_SECS: u64 = 300; // 5 minutes
pub const BROADCAST_CHANNEL_CAPACITY: usize = 1000; // buffer for peer connection notifications
